# Generated by Django 3.1.1 on 2021-09-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20210911_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='national_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='regionradius',
            name='radius',
            field=models.IntegerField(),
        ),
    ]
