# Generated by Django 3.1.1 on 2021-09-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_company', '0004_auto_20210913_0843'),
        ('taxi', '0004_auto_20210912_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schdules', to='transportation_company.contract')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schdules', to='transportation_company.request')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schdules', to='taxi.driver')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
