# Generated by Django 3.1.1 on 2021-10-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_taxischedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionpolygon',
            name='driver',
        ),
        migrations.AddField(
            model_name='regionpolygon',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='regions',
            field=models.ManyToManyField(related_name='travels', to='taxi.RegionPolygon'),
        ),
    ]
