# Generated by Django 3.1.1 on 2021-09-08 03:54

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('full_name', models.TextField(max_length=100)),
                ('emergency_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('national_code', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=6)),
                ('address_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manager_full_name', models.CharField(max_length=30)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('time_shifts', models.JSONField(default=dict)),
                ('manager_mobile', models.CharField(max_length=30)),
                ('manager_national_number', models.TextField(max_length=100)),
                ('working_time', models.JSONField(default=dict)),
                ('address', models.JSONField(default=dict)),
                ('address_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('deputy_mobile', models.CharField(max_length=30)),
                ('deputy_full_name', models.CharField(max_length=30)),
                ('service_officer', models.JSONField(default=dict)),
                ('avatar', models.ImageField(upload_to='')),
                ('postal_code', models.TextField(max_length=100)),
                ('student_count', models.IntegerField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('full_name', models.TextField(max_length=100)),
                ('national_code', models.TextField(max_length=100)),
                ('gender', models.CharField(max_length=5)),
                ('student_code', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='school.parent')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
