# Generated by Django 3.1.1 on 2021-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210912_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('part', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='levels',
            field=models.ManyToManyField(related_name='schools', to='school.Level'),
        ),
    ]
