# Generated by Django 3.1.1 on 2021-09-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210913_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
