# Generated by Django 3.1.1 on 2021-09-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210920_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='time_shifts',
        ),
        migrations.RemoveField(
            model_name='school',
            name='working_time',
        ),
        migrations.AddField(
            model_name='level',
            name='working_time',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(default=dict),
        ),
        migrations.AlterField(
            model_name='school',
            name='service_officer',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
