# Generated by Django 3.1.1 on 2021-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20210920_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='working_time',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
