# Generated by Django 3.1.1 on 2021-09-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210920_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='part',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
