# Generated by Django 3.1.1 on 2021-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20210928_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
