# Generated by Django 3.1.1 on 2021-06-08 16:59

from django.db import migrations, models
import media_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_auto_20210608_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=media_app.models.user_directory_path),
        ),
    ]
