# Generated by Django 3.1.1 on 2021-09-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_company', '0002_auto_20210912_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='transportation_company.contract'),
        ),
    ]
