# Generated by Django 3.1.1 on 2021-09-13 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_company', '0003_auto_20210912_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='company',
        ),
        migrations.AddField(
            model_name='contract',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sweep_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 8, 43, 35, 441371, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sweep_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 8, 43, 48, 221014, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installment',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='transportation_company.installment'),
        ),
    ]
