# Generated by Django 3.1.1 on 2021-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_company', '0004_auto_20210913_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivercontract',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='service_type',
            field=models.CharField(choices=[('single_pass', 'single'), ('multiple_pass', 'multiple'), ('service', 'service')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20),
        ),
    ]
